# Create a deployment. This will deploy our app on multiple nodes.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remindmeweb-deployment # name of our deployment
spec:
  selector:
    matchLabels:
      app: remindmeweb # I'll deploy to all pods that have this label
  replicas: 2 # run our app on 2 pods please!
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: remindmeweb # Label of the pods created by this template
    spec:
      containers:
        - name: frontend2 # name of container
          image: kubernetessuccinctly/remind-me-web:2.0.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM # This variable tells the service to find service host information from dns service. You can change this value to 'env' to query service hosts from environment variables.
              value: dns
            - name: apiUrl # This environment variable is used by the application to connect to the API
              value: http://remindmeapi-statefulset-0.remind-me-api-svc.default.svc.cluster.local
          ports:
            - containerPort: 80
              protocol: TCP
---
# Describe a service that consists of our web app pods
apiVersion: v1
kind: Service
metadata:
  name: remind-me-web-svc
  labels:
    app: remind-me-web-svc
spec:
  type: NodePort # type of service
  ports:
    - port: 8080 # any service in the same namespace can talk to this service using this port.
      protocol: TCP
      targetPort: 80 # our web application is running on this port in pod. By default, targetPort = port.
      nodePort: 31120 # external users can access this service on port 31120 using kube-proxy.
  selector:
    app: remindmeweb
