apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: remindmeautoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: remindmeweb-deployment
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
---
